[build]
builder = "NIXPACKS"
installCommand = "npm install && apt-get update && apt-get install -y libglib2.0-0 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm1 libasound2 libpangocairo-1.0-0 libxss1 libgtk-3-0 libxshmfence1 libglu1-mesa"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/api/status"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
