[build]
builder = "NIXPACKS"

[build]
installCommand = "npm install"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/api/status"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
